server:
  port: 8800

spring:
  security:
    basic:
      enabled: true
    user:
      name: root
      password: booszy
  application:
    name: lanxin-conf-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xylanxincyh/lanxin-conf-pro
          searchPaths: lanxin-conf-pro
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
        ip-address: true
