server:
  port: 8900

spring:
  application:
    name: lanxin-conf-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xylanxincyh/lanxincloud
          search-paths: /lanxin-master/lanxin-conf-pro/**
          username:
          password:

    consul:
      host: localhost
      port: 8500
