server:
  port: 8088
spring:
  profiles:
    active: dev
  application:
      name: lanxin-zuul-server
  cloud:
    consul:
      host: localhost
      port: 8500
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  routes:
    lanxin-user-service: /user/**
    lanxin-dept-service: /dept/**
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
